### ISSUE TITLE
As an Urban Parks staff member I want to change the maximum number of pending park jobs accepted by the system

### ISSUE THREAD

**Issue by Saerith** [Saerith/TCSS360Group3#18]
Rule:
The maximum number of pending park jobs must be a positive integer.

Acceptance tests:
Zero is specified
A negative integer is specified
A non-integer is specified
A positive integer is specified

**Comment by abderisaq** [comment]
Should I throw an exception when the given value is 0 or negative?

I checked the Feat/big_refactor_etc branch and I don't see any exception.

**Comment by abderisaq** [comment]
in order to add this functionalty I made some changes to the given classes:

(1) Constants class:

Changed : public static final int MAX_PENDING_JOBS = 20;
To           : private int maxPendingJobs = 20;

Added new field: private String fileName = "ProgramConstants.txt";

Added setters and getters for maxPendingJobs.

Changed the constructor to:
public Constants() {
   loadData();
}

Added a new methods: loadData() and saveData()

--------------------------------------------------

(2) JobCollection class:

In this method isNumJobsAtMaximum():
Changed : return pendingJobs >= Constants.MAX_PENDING_JOBS;
To           : Constants constants = new Constants();
		 return pendingJobs >= constants.getMaxPendingJobs();



--------------------------------------------------

**Comment by walkhh** [comment]
Looks good but in loadData() it prints an error when the data can't be loaded. Messages should only be shown in view classes. For the GUI, errors not related to user input like this could be in messagebox (popup) windows, I dunno.
And when loadData fails nothing happens. The program should exit or a default value should be loaded.
Also, private String fileName should be private static final String programConstantsFile or something since it doesn't change.
The value given to setMaxPendingJobs should be checked before sending it. (Precondition)

**Comment by abderisaq** [comment]
Thanks Walker,

I made the changes:

(1) when loadData() fails I am assigning the default value to maxPendingJobs which is 20

(2) Changed the fileName to private static final.

(3) I added in the comment the precondition. 

Do you think I should remove the if condition from setMaxPendingJobs()?

**Comment by walkhh** [comment]
From friday: If checking a precondition violation inside a method is easy to do, do it and throw an exception if it is violated.
I don's know if that contradicts what I said earlier but yeah, replace return false with throwing an out of range exception or something, OR just not check it.
